# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install build dependencies and runtime dependencies
RUN apk add --no-cache gcc musl-dev linux-headers

WORKDIR /app

# Copy the project files
COPY . .

# Upgrade pip and install the project using pip. Using --no-cache-dir to reduce size.
RUN pip install --upgrade pip && \
    pip install --no-cache-dir .

# Expose port if necessary (optional, MCP works over stdio though)

CMD ["llm-bridge-mcp"]
